### ISSUE TITLE
Line 209 `who am i` on Raspberry Pi

### ISSUE THREAD

**Issue by jonwitts** [aoakley/cotswoldjam#6]
https://github.com/aoakley/cotswoldjam/blob/800d93d0d3845daf03c0c7ba4067809ad05dee90/raspbian-shrink/raspbian-shrink#L209

Line 209 on a Raspberry Pi does not return the current user, however changing it to "CALLER=`who | awk '{print $1}'`" does...

Thanks,
Jon

**Comment by aoakley** [comment]
Thanks, I'll sort that when I get a moment.

It works on Ubuntu 16.04, what distro are you using?

**Comment by jonwitts** [comment]
Tested at at work on the x86 Raspbian running in a VM. Screen grab below from my Ubuntu 17.04 install at home...

![screenshot from 2017-09-06 20-12-22](https://user-images.githubusercontent.com/8962587/30130054-df0fb310-933f-11e7-8910-3ced78d053a7.png)

**Comment by jonwitts** [comment]
And then again on my home machine running as root...

Rather than "who am i" I think the command is "whoami" but that will not return the user who executed the script as root...

![screenshot from 2017-09-06 20-15-43](https://user-images.githubusercontent.com/8962587/30130197-5628e6ce-9340-11e7-8598-a5e862d17663.png)
![screenshot from 2017-09-06 20-17-22](https://user-images.githubusercontent.com/8962587/30130239-6ea7da70-9340-11e7-96f0-c84a7f02dfe1.png)

Great script by the way!
